SPELLING_FIXES = {
    "Abdomenal Pediatric Set": "Abdominal Pediatric Set",
    "Abdomenal Retractor مبعد بطن": "Abdominal Retractor مبعد بطن",
    "Abdominal Maliable مسطره مولايبل": "Abdominal Malleable مسطره مولايبل",
    "Adison Toothed forcep": "Adson Toothed Forceps",
    "Adison toothed forcep": "Adson toothed Forceps",
    "Aligator Forceps": "Alligator Forceps",
    "Alis foreceps": "Allis Forceps",
    "Allis Forceps      اليس": "Allis Forceps اليس",
    "Allis Forceps   اليس": "Allis Forceps اليس",
    "Anuo Scope مبعد شرجي": "Ano Scope مبعد شرجي",
    "Aortic Clamp Staight": "Aortic Clamp Straight",
    "Appendex Forceps جفت زائده": "Appendix Forceps جفت زائده",
    "Appendix Forceps  جفت زائدة": "Appendix Forceps جفت زائدة",
    "Artery Curved    ارتري": "Artery Curved ارتري",
    "Artery Curved   ارتري": "Artery Curved ارتري",
    "Artery Curved   ارتري منحني": "Artery Curved ارتري منحني",
    "Artery Forceps   ارتري منحني": "Artery Forceps ارتري منحني",
    "Artery Forceps  ارتري": "Artery Forceps ارتري",
    "Artery Straight  ارتري مستقيم": "Artery Straight ارتري مستقيم",
    "Artery straight forceps": "Artery straight Forceps",
    "Artery street forceps": "Artery street Forceps",
    "Atrery Forceps St Large": "Artery Forceps St Large",
    "Atrery Forceps St Samll": "Artery Forceps St Samll",
    "Atruamatic Forceps": "Atraumatic Forceps",
    "Babcock Forceps    باكوك": "Babcock Forceps باكوك",
    "Babcock Forceps  باكوك": "Babcock Forceps باكوك",
    "Baipolar Cable": "Bipolar Cable",
    "Bercifascial Closure ماسك ابر مناظير": "Berci Fascial Closure ماسك ابر مناظير",
    "Bobcock باكوك": "Babcock باكوك",
    "Bone Curette  معلقه كحت": "Bone Curette معلقه كحت",
    "Bone Nippler": "Bone Nibbler",
    "Bulldog staright": "Bulldog Straight",
    "Casper": "Caspar",
    "Chest Retractor Flixsable": "Chest Retractor Flexible",
    "Clamp Curved  كلامب منحني": "Clamp Curved كلامب منحني",
    "Claw Forcep كلاو": "Claw Forceps كلاو",
    "Clowar Blade Blant": "Cloward Blade Blunt",
    "Clowar Blade Blunt": "Cloward Blade Blunt",
    "Clowar Blade Sharp": "Cloward Blade Sharp",
    "Clowar Hand": "Cloward Hand",
    "Currat": "Curette",
    "Currate": "Curette",
    "De bakey Aortic Aneurysm Clamp": "DeBakey Aortic Aneurysm Clamp",
    "Debakey Aortic Aneurysm Clamp": "DeBakey Aortic Aneurysm Clamp",
    "Debakey Atrauma Clamp": "DeBakey Atrauma Clamp",
    "Debakey Forceps": "DeBakey Forceps",
    "Debakey Forceps 18mm": "DeBakey Forceps 18mm",
    "Debakey Forceps Long": "DeBakey Forceps Long",
    "Debakey Forceps Short": "DeBakey Forceps Short",
    "Debakey Forceps جفت دبيكي": "DeBakey Forceps جفت دبيكي",
    "Debakey crv": "DeBakey crv",
    "Debakeys Forcep": "DeBakey Forceps",
    "Dicector": "Dissector",
    "Dicector Sharp": "Dissector Sharp",
    "Dissecting Scissor": "Dissecting Scissors",
    "Dissecting Scissor مقص": "Dissecting Scissors مقص",
    "Dissecting scissor": "Dissecting Scissors",
    "Dissecting scissor   مقص": "Dissecting Scissors مقص",
    "Dissecting scissor  مقص": "Dissecting Scissors مقص",
    "Dissecting scissor Left": "Dissecting Scissors Left",
    "Dissecting scissor Left": "Dissecting Scissors Left",
    "Dissecting scissor Right": "Dissecting Scissors Right",
    "Dissecting scissor up": "Dissecting Scissors up",
    "Dissection Scissors  مقص": "Dissection Scissors مقص",
    "Doval": "Duval",
    "Extention": "Extension",
    "Foot Plate Rouler": "Foot Plate Ruler",
    "Foot Plate Ruller": "Foot Plate Ruler",
    "Forcelim forcep": "Forceps Forceps",
    "Gresping forceps": "Grasping Forceps",
    "Hoklet Casber": "Hooklet Caspar",
    "Hummer": "Hammer",
    "Insaflator Caple خرطوم نفخ": "Insufflator Cable خرطوم نفخ",
    "Intestinal Forceps Curved  كلامب امعاء منحني": "Intestinal Forceps Curved كلامب امعاء منحني",
    "Kerison 2 mm": "Kerrison 2 mm",
    "Kerrision 2mm": "Kerrison 2mm",
    "Kirrison 1mm": "Kerrison 1mm",
    "Kocher Curved  كوخر منحني": "Kocher Curved كوخر منحني",
    "Kocher Straight  كوخر": "Kocher Straight كوخر",
    "Kocher Stright Forseps": "Kocher Straight Forceps",
    "Kocher straight  كوخر مستقيم": "Kocher straight كوخر مستقيم",
    "Langenbeck Retractor  لانجيابيك": "Langenbeck Retractor لانجيابيك",
    "Langenbeck Retractor  لانجيلبيك": "Langenbeck Retractor لانجيلبيك",
    "Lengenbeck Retractor": "Langenbeck Retractor",
    "Macdonal": "MacDonald",
    "Major Surgery  Set  ( 5 )": "Major Surgery Set ( 5 )",
    "Masbar مسبر": "Probe مسبر",
    "Mayo Dissecting Scissor": "Mayo Dissecting Scissors",
    "Mayo Dissecting Scissor مقص": "Mayo Dissecting Scissors مقص",
    "Mayo Scissor": "Mayo Dissecting Scissors",
    "Mayo Scissor      مقص": "Mayo Dissecting Scissors مقص",
    "Mayo Scissor     مقص": "Mayo Dissecting Scissors مقص",
    "Mayo Scissor  مقص": "Mayo Dissecting Scissors مقص",
    "Mayo Scissor Curved": "Mayo Dissecting Scissors",
    "Mayo Scissor مقص": "Mayo Dissecting Scissors مقص",
    "Mayo Scissors Curve": "Mayo Dissecting Scissors",
    "Mayo Scissors Straight": "Mayo Dissecting Scissors",
    "Mayo Scissors مقص": "Mayo Dissecting Scissors مقص",
    "Mayo scissor": "Mayo Scissors",
    "Mayo scissor Straight": "Mayo Scissors Straight",
    "Mets Scissor مقص": "Metz Scissors مقص",
    "Metz Scissor": "Metz Scissors",
    "Micro Scissor 45": "Micro Scissors 45",
    "Micro Scissor 90": "Micro Scissors 90",
    "Micro Scissor Angled 18": "Micro Scissors Angled 18",
    "Micro scissior Curved": "Micro Scissors Curved",
    "Micro scissor Curved": "Micro Scissors Curved",
    "Micro scissor Straight": "Micro Scissors Straight",
    "Micro scissor angled": "Micro Scissors angled",
    "Mosquito  Curved  مسكيتو منحني": "Mosquito Curved مسكيتو منحني",
    "Mosquito  straight مسكيتو مستقيم": "Mosquito straight مسكيتو مستقيم",
    "Mosquito Forceps  ST": "Mosquito Straight مسكيتو مستقيم",
    "Mosquito Forceps Staight": "Mosquito Straight مسكيتو مستقيم",
    "Mosquito Forceps Striaght مسكيتو مستقيم": "Mosquito Forceps Straight مسكيتو مستقيم",
    "Mosquito Forceps streight": "Mosquito Forceps Straight",
    "Mosqute Curve": "Mosquito Curve",
    "Mosqute straight": "Mosquito straight",
    "Mosqutio Forceps Short": "Mosquito Forceps Short",
    "Mosqyito Curved": "Mosquito Curved",
    "Nasal Scissor": "Nasal Scissors",
    "Needle Holder  ماسك ابر": "Needle Holder ماسك ابر",
    "Non Toothed forcep": "Non Toothed Forceps",
    "Non Toothed forceps": "Non Toothed Forceps",
    "Non Toothed forceps  جفت بدون سن": "Non Toothed Forceps جفت بدون سن",
    "Ovam Forceps": "Ovum Forceps",
    "Potts Scissor": "Potts Scissors",
    "Preiosteal Elevator": "Periosteal Elevator",
    "Preiosteal elevator": "Periosteal elevator",
    "Punch Dowen": "Punch Down",
    "Punch Dowen 4mm": "Punch Down 4mm",
    "Punch biopsy forcep": "Punch biopsy Forceps",
    "Removal Rib Set  (2)": "Removal Rib Set (2)",
    "Resano Forceps": "Rozano Forceps",
    "Retractor Liver  Set": "Retractor Liver Set",
    "Richardson Retractor  مبعد ريداكشن": "Richardson Retractor مبعد ريداكشن",
    "Right Angel": "Right Angle",
    "Right Angle    رايت انجل": "Right Angle رايت انجل",
    "Right Angle   رايت انجل": "Right Angle رايت انجل",
    "Right Angle  رايت انجل": "Right Angle رايت انجل",
    "Right Angle Forcep": "Right Angle Forceps",
    "Ruller": "Ruler",
    "Scalpel Hand (3)": "Scalpel Handle No. 3",
    "Scalpel Hand (4)": "Scalpel Handle No. 4",
    "Scalpel Handle NO.1   يد مشرط": "Scalpel Handle NO.1 يد مشرط",
    "Scalpel Handle NO.4    يد مشرط": "Scalpel Handle NO.4 يد مشرط",
    "Scalple Hand": "Scalpel Hand",
    "Scalple Handle": "Scalpel Handle",
    "Scissor": "Scissors",
    "Scissor  Forceps": "Scissors Forceps",
    "Scissor Curved": "Scissors Curved",
    "Scissor Left": "Scissors Left",
    "Scissor Up": "Scissors Up",
    "Scissor and Needle": "Scissors and Needle",
    "Scissor مقص": "Scissors مقص",
    "Scissore Straight": "Scissors Straight",
    "Scissors Angeled 45": "Scissors Angled 45",
    "Scisssors Curved Right": "Scissors Curved Right",
    "Self retaning": "Self Retaining",
    "Septum Staightening Forceps": "Septum Straightening Forceps",
    "Snager": "Snare",
    "Snair": "Snare",
    "Spong Forceps": "Sponge Forceps",
    "Sponge Forcep": "Sponge Forceps",
    "Sponge Forceps    ماسك شاش": "Sponge Forceps ماسك شاش",
    "Sponge forceps": "Sponge Forceps",
    "SpongeForceps": "Sponge Forceps",
    "Spoon Forseps Dia Straight": "Spoon Forceps Dia Straight",
    "Spoon Forseps Up": "Spoon Forceps Up",
    "Stanesky  Forceps Long": "Satinsky Forceps Long",
    "Stanesky forceps": "Satinsky Forceps",
    "Sternnum Saw Rapid Act": "Sternum Saw Rapid Act",
    "Stitch Scissor": "Stitch Scissors",
    "Straight Scissor": "Straight Scissors",
    "Suction  tube": "Suction tube",
    "Tissue Forceps Non  Toothed": "Tissue Forceps Non Toothed",
    "Tongue Blade  1": "Tongue Blade 1",
    "Tongue Blade  2": "Tongue Blade 2",
    "Tongue Blade  3": "Tongue Blade 3",
    "Tonotomy Scissor": "Tenotomy Scissors",
    "Toothed forcep": "Toothed Forceps",
    "Toothed forcep  جفت بسن": "Toothed Forceps جفت بسن",
    "Towel Clip": "Towel Forceps",
    "Towel Clip تاول كلبس": "Towel Forceps تاول كلبس",
    "Towel Clips": "Towel Forceps",
    "Towel Clips تاول كلبس": "Towel Forceps تاول كلبس",
    "Towel Forceps     تاول كلبس": "Towel Forceps تاول كلبس",
    "Trifect Valve Series Sizer Set Model TF 2000-2": "Trifecta Valve Series Sizer Set Model TF 2000-2",
    "Trocar 10 mm  تروكر": "Trocar 10 mm تروكر",
    "Vein Retractor  مبعد عصب": "Vein Retractor مبعد عصب",
    "Wrigly Forceps": "Wrigley Forceps",
    "Yankar Suction": "Yankauer Suction",
    "Yankar Suction  بوز شفاط": "Yankauer Suction بوز شفاط",
    "Yanker Suction": "Yankauer Suction",
    "Yanker Suction بوز شفاط": "Yankauer Suction بوز شفاط",
    "Yankuer Suction": "Yankauer Suction",
    "Yunker Suctin": "Yankauer Suction",
    "Yunker Suction": "Yankauer Suction",
    "adson blue": "Adson Blue",
    "aortoc set": "Aortic set",
    "battery cover": "Battery Cover",
    "curette": "Curette",
    "dilator": "Dilator",
    "https://ips.klsmartin.com/ui/terms.": "Https://Ips.Klsmartin.Com/Ui/Terms.",
    "https://www.klsmartin.com/en/general-conditions-of-sale.": "Https://Www.Klsmartin.Com/En/General-Conditions-Of-Sale.",
    "morris retractor": "Morris Retractor",
    "mosquito curved  مسكيتو منحني": "mosquito curved مسكيتو منحني",
    "needle holder ماسك ابر": "Needle Holder ماسك ابر",
    "preforator": "Perforator",
    "saw hand": "Saw Hand",
    "snare": "Snare",
    "sponge forceps": "sponge Forceps",
    "to have knowledge of by accepting this offer.": "To Have Knowledge Of By Accepting This Offer.",
    "toothed": "Toothed",
    "twister needle": "Twister Needle",
}

def clean_name(name):
    if not name or str(name).lower() == 'nan':
        return name
        
    name_str = str(name).strip()
    
    # 1. Apply specific spelling dictionary fixes (case-insensitive keys)
    lower_fixes = {k.lower(): v for k, v in SPELLING_FIXES.items()}
    if name_str.lower() in lower_fixes:
        name_str = lower_fixes[name_str.lower()]
    
    # 2. Capitalize first letter of each word (Title Case)
    import re
    def repl(m):
        w = m.group(0)
        return w if w.isupper() else w.capitalize()
    name_str = re.sub(r'[A-Za-z]+', repl, name_str)
    
    # 3. Fix multiple spaces and strip
    name_str = re.sub(r'\s+', ' ', name_str).strip()
    
    return name_str
