# core/constants.py

CATEGORY_MAPPING = {
    "08": "08 - Electrosurgery accessories (mains cables, power meters)",
    "10": "10 - Scalpels (handles, blades)",
    "11": "11 - Scissors",
    "12": "12 - Forceps (tissue/dissecting forceps)",
    "13": "13 - Haemostatic/artery forceps",
    "14": "14 - Cotton swab / dressing forceps",
    "15": "15 - Retractors, wound spreaders",
    "16": "16 - Probes, applicators, spatulas",
    "17": "17 - Headlights (MedLED Spectra/Chrome)",
    "18": "18 - Suction tubes, cannulas",
    "20": "20 - Needle holders",
    "21": "21 - Dressings (plaster shears/scissors)",
    "22": "22 - Bone surgery / trauma instruments, misc. (side cutters)",
    "23": "23 - Bone surgery (chisels, rongeurs, raspatories)",
    "24": "24 - Minimally invasive/cardiac instruments (marCore, bulldog clamps, punches)",
    "25": "25 - Implants - Craniomaxillofacial surgery (LevelOne Fixation plates/meshes)",
    "26": "26 - Implants - Hand (Linos plates)",
    "28": "28 - Goitre, dermatology instruments",
    "30": "30 - Stomach, intestines, rectum instruments",
    "32": "32 - Gynecology",
    "33": "33 - Obstetrics",
    "37": "37 - Rhinology",
    "38": "38 - Special instruments for craniomaxillofacial surgery",
    "39": "39 - Tonsillectomy, laryngo-bronchoscopy",
    "42": "42 - Mouth and laryngeal mirrors",
    "43": "43 - Instruments for extraction / dental (tooth) forceps",
    "44": "44 - Filling instruments (dental)",
    "46": "46 - Impression trays, carving instruments",
    "47": "47 - Technic pliers",
    "50": "50 - General bone instruments (bending/cutting pliers for implant systems)",
    "51": "51 - Distractors and fixators",
    "52": "52 - Biomaterials - SonicWeld Rx",
    "55": "55 - Implants CMF - instruments/storage accessories",
    "56": "56 - Miscellaneous (stainless steel receptacles/trays)",
    "80": "80 - Electrosurgery (units, bipolar vessel sealing)",
    "84": "84 - Surgical laser systems",
    "89": "89 - Medical lights (marLED examination/surgical lights)"
}
BROCHURE_HIERARCHY = {
    "Surgical Laser Systems":[
        "Precision You Trust, Safety You Rely On."
    ],
    "Plastic Surgery":[
        ""
    ],
    "Neurosurgery":[
        ""
    ],
    "Oral and Maxillofacial Surgery":[
        ""
    ],

    "Traumatic Surgery": [
        "Headless Cannulated Compression Screws €“ Resorbable",
        "Maxillomandibular Fixation (MMF System)",
        "Thoracic Fixation System",

    ],
    "Hand Surgery": [
        "Forearm Reconstruction",
        "Improving On The Tried, Tested And Proven",
        "Management Of Failed Sauve-Kapandji Procedures",
        "Lean. Complete. New!",
        "Product Overview",
        "Product Overview Traumatology",
        "Simply Clever!",
        "Special Instruments For Hand Surgery",
        "Ulna Shortening And Radius Reconstruction System",
        "Ulnar Head Prosthesis",
    ],
    "CMF Surgery": [
        "1.5-Mm Neuro Plating System", 
        "A Comprehensive Solution For Osteosynthesis In The Midface",
        "A Real Surface Replacement!",
        "Anatomically Pre-Shaped Midface And Mandibular Implants",
        "Angled Screwdriver",
        "Biomaterials Marpor®",
        "Cranial Distraction",
        "Cranial Springs For The Treatment Of Sagittal Craniosynostoses",
        "Cranium",
        "Designed In Cooperation With Dr. William Arnett, Santa Barbara, Ca",
        "Distraction",
        "Epithesis Base",
        "For Mediocarpal Partial Arthrodeses",
        "In Collaboration With Dr. Klauser",
        "MBM Bone Mill",
        "Mandible External Fixation System",
        "Maxillomandibular Fixation (MMF System)",
        "Midface Orbita",
        "Midface Osteosynthesis",
        "Modular External Distraction System",
        "Neuro Osteosynthesis",
        "New Horizons In Horizontal Mandibular Distraction",
        "Orthodontic Implants",
        "Orthognathic Surgery",
        "Osteosynthese 2.3 Fracture And Reconstruction",
        "Osteosynthesis 1.0 Micro",
        "Osteosynthesis 1.5 Micro",
        "Osteosynthesis 2.0 Mini",
        "Osteosynthesis 2.0-2.7 Fracture And Reconstruction Threadlock Ts",
        "Osteosynthesis System",
        "Portfolio Overview",
        "Quick Guide",
        "Resection Guides For Mandibular Reconstruction With Fibula Graft",
        "Rigid External Distraction",
        "Sophisticated Solutions In CMF Surgery",
        "Sophisticated Transversal Distractors In CMF Surgery",
        "Special Instruments For The Endoscopic Restoration Of Fractures Of The Temporo-Mandibular Joint",
        "Standard Approach Mesh Pre Contoured Titanium Mesh Implants",
        "Supplementary Products",
        "Surgical Technique",
        "Surgical Techniques And Product Range",
    ],

    "Electrosurgery": [
        "A New Dimension In Intelligent Vessel Sealing",
        "Accessories For Electrosurgery",
        "Marclamp® IQ Instruments And Maxium",
        "Marseal® 5 Plus Maryland",
        "Proven Technology From Kls Martin",
        "Rigid And Flexible Probes For Open And Endoscopic Argon Surgery",
        "Safe And Easy Operating With The Kls Martin Bipolar Instruments",
        "Safe And Simple!",
        "Seal, Cut, Clean, Repeat!",
        "Simplicity Meets Excellence In Vessel Sealing",
        "The Best Combination Between Economy And Safe Application!",
        "The Bipolar Kls Martin Scissors For Use In Open Surgery",
        "The Compact Class For Monopolar And Bipolar HF Applications",
        "The Compact Electrosurgical Unit With High Capacity",
        "The Innovative System For Efficient Smoke Evacuation",
        "The New Bipolar Forceps From Kls Martin €“ With Nonstick Effect And A Revolutionary Ergonomic Design",
        "The Smart Choice For Every Or",
        "The System For Bipolar Vessel Sealing For Open And Laparoscopic Surgery",
        "The Touch Of Simplicity",
        "Touch And Feel The Difference!",
        "Version Mmb And Mbb"
    ],
    "Accessories": [
        "Accessories Catalog",
        "Accessory Catalog For Ceiling Supply Units",
        "Ceiling Supply Solutions For Operating Theaters And Intensive Care Units",
        "Customized Storage System",
        "Foot Switches HF Devices",
        "Healthcare Design Technology",
        
    ],
    "Cardio, Thoracic and Vascular Surgery": [
        "Ergonomic And Flexible!",
    ],
    "Headlights":[
        "Cordless Surgical Headlight"
    ],
    "Operating Lights ":[
        "For Marled® Operating Lights",
        "Operating Light €“ Xtremely Different",
        "Show How Efficient Light Can Be.",
        "Small Light €“ Big Effect!",
        "Standard Configurations Of The E- And X-Series",
    ],
    "Dental Surgery":[
        "Dental Applications",
        "Transformation",

    ],
    "General Surgery":[
        "How To Find Us",
        "Retractor System",
        "Rhombic 3D Condylar Fracture Plate",
        "Suggested Surgical Instrument Sets",
        "Tray Systems"

    ],
}


ALL_AVAILABLE_BROCHURES = [
    """1.5-Mm Neuro Plating System""",
    """A Comprehensive Solution For Osteosynthesis In The Midface""",
    """A New Dimension In Intelligent Vessel Sealing""",
    """A Real Surface Replacement!""",
    """Accessories Catalog""",
    """Accessories For Electrosurgery""",
    """Accessory Catalog For Ceiling Supply Units""",
    """Anatomically Pre-Shaped Midface And Mandibular Implants""",
    """Angled Screwdriver""",
    """Biomaterials Marpor®""",
    """Cardio, Thoracic and Vascular Surgery""",
    """Ceiling Supply Solutions For Operating Theaters And Intensive Care Units""",
    """Cordless Surgical Headlight""",
    """Cranial Distraction""",
    """Cranial Springs For The Treatment Of Sagittal Craniosynostoses""",
    """Cranium""",
    """Customized Storage System""",
    """Dental Applications""",
    """Designed In Cooperation With Dr. William Arnett, Santa Barbara, Ca""",
    """Distraction""",
    """Epithesis Base""",
    """Ergonomic And Flexible!""",
    """Foot Switches HF Devices""",
    """For Marled® Operating Lights""",
    """For Mediocarpal Partial Arthrodeses""",
    """Forearm Reconstruction""",
    """General Surgery""",
    """Headless Cannulated Compression Screws €“ Resorbable""",
    """Headlights""",
    """Healthcare Design Technology""",
    """How To Find Us""",
    """Improving On The Tried, Tested And Proven""",
    """In Collaboration With Dr. Klauser""",
    """Lean. Complete. New!""",
    """MBM Bone Mill""",
    """Management Of Failed Sauve-Kapandji Procedures""",
    """Mandible External Fixation System""",
    """Marclamp® IQ Instruments And Maxium""",
    """Marseal® 5 Plus Maryland""",
    """Maxillomandibular Fixation (MMF System)""",
    """Midface Orbita""",
    """Midface Osteosynthesis""",
    """Modular External Distraction System""",
    """Neuro Osteosynthesis""",
    """Neurosurgery""",
    """New Horizons In Horizontal Mandibular Distraction""",
    """Operating Light €“ Xtremely Different""",
    """Oral and Maxillofacial Surgery""",
    """Orthodontic Implants""",
    """Orthognathic Surgery""",
    """Osteosynthese 2.3 Fracture And Reconstruction""",
    """Osteosynthesis 1.0 Micro""",
    """Osteosynthesis 1.5 Micro""",
    """Osteosynthesis 2.0 Mini""",
    """Osteosynthesis 2.0-2.7 Fracture And Reconstruction Threadlock Ts""",
    """Osteosynthesis System""",
    """Plastic Surgery""",
    """Portfolio Overview""",
    """Precision You Trust, Safety You Rely On.""",
    """Product Overview""",
    """Product Overview Traumatology""",
    """Proven Technology From Kls Martin""",
    """Quick Guide""",
    """Resection Guides For Mandibular Reconstruction With Fibula Graft""",
    """Retractor System""",
    """Rhombic 3D Condylar Fracture Plate""",
    """Rigid And Flexible Probes For Open And Endoscopic Argon Surgery""",
    """Rigid External Distraction""",
    """Safe And Easy Operating With The Kls Martin Bipolar Instruments""",
    """Safe And Simple!""",
    """Seal, Cut, Clean, Repeat!""",
    """Show How Efficient Light Can Be.""",
    """Simplicity Meets Excellence In Vessel Sealing""",
    """Simply Clever!""",
    """Small Light €“ Big Effect!""",
    """Sophisticated Solutions In CMF Surgery""",
    """Sophisticated Transversal Distractors In CMF Surgery""",
    """Special Instruments For Hand Surgery""",
    """Special Instruments For The Endoscopic Restoration Of Fractures Of The Temporo-Mandibular Joint""",
    """Standard Approach Mesh Pre Contoured Titanium Mesh Implants""",
    """Standard Configurations Of The E- And X-Series""",
    """Sterilization Container-And Tray Systems""",
    """Suggested Surgical Instrument Sets""",
    """Supplementary Products""",
    """Surgical Technique""",
    """Surgical Techniques And Product Range""",
    """The Best Combination Between Economy And Safe Application!""",
    """The Bipolar Kls Martin Scissors For Use In Open Surgery""",
    """The Compact Class For Monopolar And Bipolar HF Applications""",
    """The Compact Electrosurgical Unit With High Capacity""",
    """The Innovative System For Efficient Smoke Evacuation""",
    """The New Bipolar Forceps From Kls Martin €“ With Nonstick Effect And A Revolutionary Ergonomic Design""",
    """The Smart Choice For Every Or""",
    """The System For Bipolar Vessel Sealing For Open And Laparoscopic Surgery""",
    """The Touch Of Simplicity""",
    """Thoracic Fixation System""",
    """Touch And Feel The Difference!""",
    """Transformation""",
    """Tray Systems""",
    """Ulna Shortening And Radius Reconstruction System""",
    """Ulnar Head Prosthesis""",
    """Version Mmb And Mbb""",
]

APP_VERSION = "1.18"
GITHUB_REPO = "Anasmo1323/KLSMartin_TeamAssistant"